
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 01 16:35:42 CET 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 12;
  public static final int LT = 13;
  public static final int NE = 16;
  public static final int SEMICOLON = 22;
  public static final int RBRACE = 25;
  public static final int OR = 11;
  public static final int INT = 5;
  public static final int CHAR = 6;
  public static final int LEFTPAR = 20;
  public static final int LOOP = 3;
  public static final int RIGHTPAR = 21;
  public static final int LBRACE = 24;
  public static final int GT = 17;
  public static final int ID = 9;
  public static final int LE = 14;
  public static final int COMMA = 23;
  public static final int FLOAT = 7;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int GE = 18;
  public static final int CONST = 10;
  public static final int error = 1;
  public static final int ASSIGN = 19;
  public static final int EQ = 15;
  public static final int BOOL = 8;
  public static final int REDO = 4;
}

